version: '3.8'

services:
  db:
    container_name: postgres
    build:
      context: ./
      dockerfile: ./scripts/db/Dockerfile
    ports:
      - '5455:5432'
    volumes:
      - /var/folders/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - corp

networks:
  corp:
    driver: bridge
